#!/usr/bin/env ruby

require 'rbconfig'

def bench_one(name)
  lib = File.join(File.dirname(__FILE__), name)
  cmd = %{
    $REDSHIFT_CLIB_NAME = "#{name}"
    puts "#{name}:"
    #{name.split(/[-_]/).map {|w|w.capitalize}.join}.do_bench {|l| puts l}
  }
  ruby = Config::CONFIG["RUBY_INSTALL_NAME"]
  system ruby, "-r" , "./bench", "-r", lib, "-e", cmd
end

pat = ARGV.pop
pat = pat ? Regexp.new(pat) : //
%w{
  alg-state
  algebraic
  connect
  continuous
  discrete
  euler
  formula
  half-strict
  inertness
  linked-flows
  queues
}.grep(pat).each do |name|
  bench_one(name)
end
