#!/usr/bin/env ruby

def bench_one(name)
  lib = File.join(File.dirname(__FILE__), name)
  cmd = %{
    $REDSHIFT_CLIB_NAME = "#{name}"
    puts "#{name}:"
    #{name.capitalize}.do_bench {|l| puts l}
  }
  system "ruby", "-r" , "./bench", "-r", lib, "-e", cmd
end

pat = ARGV.pop
pat = pat ? Regexp.new(pat) : //
["continuous",
 "discrete"].grep(pat).each do |name|
  bench_one(name)
end
