#!/usr/bin/env ruby

require 'my-profile.rb'

class Object
  def rbprofile prof_flag = true
    if block_given?
      $profiler.instance_eval do
        save = @do_profiling
        @do_profiling = prof_flag
        yield
        @do_profiling = save
      end
    else
      $profiler.instance_eval {@do_profiling = prof_flag}
    end
  end
end

bench_flag = ARGV.delete("b") || ARGV.delete("bench")
profile_flag = ARGV.delete("p") || ARGV.delete("profile")
rbprof_flag = ARGV.delete("rbprof")

prog_name = ARGV.shift

$REDSHIFT_CLIB_NAME = prog_name

case
when bench_flag
  require prog_name; steps = $steps
  require 'benchmark'
  include Benchmark
  bm(12) do |test|
    for step in steps
      test.report(step[0] + ":") do
        step[1].call
      end
    end
  end

when profile_flag
  require prog_name; steps = $steps
  for step in steps
#    require 'profile' if step[0] == "run"  # don't profile compilation
    profile (step[0] == "run") do  # only profile run, not compile or create
      step[1].call
    end
  end

when rbprof_flag
  require 'rbprof'; rbprofile false
  require prog_name; steps = $steps
  for step in steps
    if step[0] == "run"  # don't profile compilation
      rbprofile {step[1].call}
    else
      step[1].call
    end
  end

else
  require prog_name; steps = $steps
  for step in steps
    step[1].call
  end
end
